#!/usr/bin/env bash
set -euo pipefail

# Resolve this repo's location so the stub points at our main.sh regardless
# of where the repo lives.
repo_dir=$(cd "$(dirname "${BASH_SOURCE[0]:-$0}")" && pwd)

# Optional: bake a --screenshots mount into the stub so the host dir is shared
# at /SCREENSHOTS on every run without typing the flag. Omit to opt out.
screenshots=""
while [[ $# -gt 0 ]]; do
  case "$1" in
    --screenshots) shift; [[ $# -gt 0 ]] || { echo "install.sh: --screenshots needs a path" >&2; exit 1; }; screenshots="$1" ;;
    --screenshots=*) screenshots="${1#*=}" ;;
    *) echo "install.sh: unknown argument '$1'" >&2; exit 1 ;;
  esac
  shift
done

bin_dir="$HOME/.local/bin"
target="$bin_dir/claude"

screenshots_arg=""
[[ -n "$screenshots" ]] && screenshots_arg=" --screenshots \"$screenshots\""

mkdir -p "$bin_dir"
cat > "$target" <<EOF
#!/usr/bin/env bash
# Generated by $repo_dir/install.sh — do not edit. Logic lives in main.sh.
exec "$repo_dir/main.sh" --compose-dir "$repo_dir"$screenshots_arg "\$@"
EOF
chmod +x "$target"

echo "Installed claude stub -> $target (delegates to $repo_dir/main.sh)"
[[ -n "$screenshots" ]] && echo "Baked --screenshots \"$screenshots\" (mounts at /SCREENSHOTS)."
case ":$PATH:" in
  *":$bin_dir:"*) ;;
  *) echo "Note: $bin_dir is not on your PATH." ;;
esac
