#!/usr/bin/env bash
set -euo pipefail

# Resolve this repo's location so the stub points at our main.sh regardless
# of where the repo lives.
repo_dir=$(cd "$(dirname "${BASH_SOURCE[0]:-$0}")" && pwd)

bin_dir="$HOME/.local/bin"
target="$bin_dir/claude"

mkdir -p "$bin_dir"
cat > "$target" <<EOF
#!/usr/bin/env bash
# Generated by $repo_dir/install.sh — do not edit. Logic lives in main.sh.
exec "$repo_dir/main.sh" "\$@"
EOF
chmod +x "$target"

echo "Installed claude stub -> $target (delegates to $repo_dir/main.sh)"
case ":$PATH:" in
  *":$bin_dir:"*) ;;
  *) echo "Note: $bin_dir is not on your PATH." ;;
esac
